/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import { SmartImage as SmartImage } from './components/smart-image/smart-image';

interface HTMLSmartImageElement extends SmartImage, HTMLElement {
}
declare var HTMLSmartImageElement: {
  prototype: HTMLSmartImageElement;
  new (): HTMLSmartImageElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "smart-image": HTMLSmartImageElement;
  }
  interface ElementTagNameMap {
      "smart-image": HTMLSmartImageElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "smart-image": JSXElements.SmartImageAttributes;
      }
  }
  namespace JSXElements {
      export interface SmartImageAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          preload?: string,
          width?: number,
          height?: number,
          bg?: string
      }
  }
}

